### ISSUE TITLE
How do I get all the data in the region?

### ISSUE THREAD

**Issue by MonkSoul** [MichaCo/CacheManager#227] opened 2018-04-19 03:51 UTC
```
_cache.Put("key","value","region");
_cache.Put("key1","value1","region");
_cache.Put("key2","value2","region");
...
```

I want to get all datas in the name of "region" region.  
Like this

```
var datas=_cache.GetAll("*");
```
or
```
var datas=_cache.GetAll("^key","region");
```

**Comment by MichaCo** [comment] 2018-04-19 07:44
duplicate of #225

**Closed by MichaCo** 2018-04-19 07:44 UTC
