### ISSUE TITLE
"Object reference not set to an instance of an object" in the MemoryCache (System.Runtime.Caching)

### ISSUE THREAD

**Issue by davenewza** [MichaCo/CacheManager#149] opened 2017-05-05 11:51 UTC
Can anyone explain why the following exception is being thrown from MemoryCache when requesting a item from our cache?

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Runtime.Caching.UsageBucket.GetFreeUsageEntry()
>    at System.Runtime.Caching.UsageBucket.AddCacheEntry(MemoryCacheEntry cacheEntry)
>    at System.Runtime.Caching.MemoryCacheStore.AddToCache(MemoryCacheEntry entry)
>    at System.Runtime.Caching.MemoryCacheStore.Set(MemoryCacheKey key, MemoryCacheEntry entry)
>    at System.Runtime.Caching.MemoryCache.Set(String key, Object value, CacheItemPolicy policy, String regionName)
>    at CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1.GetCacheItemInternal(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.GetCacheItem(String key, String region)
>    at CacheManager.Core.BaseCacheManager`1.GetCacheItemInternal(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.GetCacheItem(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.Get(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.Get[TOut](String key, String region)

The cache is configured as such:

```
cacheManager = CacheFactory.Build<IReadOnlyCollection<TAggregate>>(p => p
    // Use compressed JSON serialisation. This will only apply to the Redis handler.
    .WithGzJsonSerializer(DefaultSerializerSettings, DefaultSerializerSettings)
    // Only retry 5 times.
    .WithMaxRetries(5)
    // The in-process cache will serve aggregates straight from memory.
    .WithSystemRuntimeCacheHandle("in-process")
    // Add the backplane Redis cache handle to establish a multi-layer cache.
    .And
    // Distributed cache (Azure Redis).
    .WithRedisConfiguration("redis", $"{settings.Endpoint}:{settings.Port},password={settings.Password},ssl={settings.Ssl},abortConnect=False")
    // Set as backplane to synchronise from the other clients.
    .WithRedisBackplane("redis")
    // CacheUpdateMode.Up will synchronise the in-process cache from additions to Redis.
    .WithUpdateMode(CacheUpdateMode.Up)
    // Use this backplane cache handle.
    .WithRedisCacheHandle("redis", true)
);
```

**Comment by MichaCo** [comment] 2017-05-05 14:42
@davenewza Hi,
To be honest, I have no idea what the reason for this is. I had [a similar issue in an earlier version of the .NET framework though, which was fixed in 4.6](http://stackoverflow.com/questions/21680429/why-does-memorycache-throw-nullreferenceexception) . 

Which version are you running this on?

And do you have code to reproduce this behavior? Or is it happening just from time to time?

Thanks,
M

**Comment by davenewza** [comment] 2017-05-09 12:44
@MichaCo it was happening in one of our environments. All we had to do was repopulate that section of the key to fix it. We could not reproduce it at all. My only guess is that it was some kind of race condition between the difference cache layers, but that's really just a stab in the dark. We are using .NET 461.

**Comment by MichaCo** [comment] 2017-05-09 13:16
@davenewza ok thanks for the information. I'll try to investigate that a little bit further if I find some time. The only thing I'm doing in the get method is setting the key again in case you use sliding expiration, to keep it alive basically. Don't know though why the SystemRuntimeCache throws a NullReferenceException internally... pretty unfriendly...

Leaving this open for now, let me know if you encounter that error again. If you do, maybe use the dictionary or MS Extenstions memory cache instead

**Comment by davenewza** [comment] 2017-05-10 09:42
Thanks a bunch - I will keep a close eye on this and report back.

**Comment by davenewza** [comment] 2017-06-25 12:39
This never happened again.

**Closed** 2017-07-09 12:16 UTC
