### ISSUE TITLE
Cache hanging while trying to update

### ISSUE THREAD

**Issue by dariogriffo-fourth** [MichaCo/CacheManager#121] opened 2016-12-21 13:04 UTC
I'm using the cache with Redis, everything was fine until today the AddOrUpdate started failing for some reason
This is the log
```
info: CacheManager.Core.BaseCacheManager[0]
      Cache manager: adding cache handles...
info: CacheReflectionHelper[0]
      Creating handle redis-0 of type CacheManager.Redis.RedisCacheHandle`1[TCacheValue].
info: CacheManager.Redis.RedisConnectionManager[0]
      Trying to connect with the following configuration: 'localhost:6379,allowAdmin=False,connectTimeout=5000,ssl=False,abortConnect=False,connectRetry=10'
info: CacheManager.Core.BaseCacheManager[0]
      Cache manager: adding cache handles...
info: CacheReflectionHelper[0]
      Creating handle redis-1 of type CacheManager.Redis.RedisCacheHandle`1[TCacheValue].
info: CacheManager.Core.BaseCacheManager[0]
      Cache manager: adding cache handles...
info: CacheReflectionHelper[0]
      Creating handle redis-2 of type CacheManager.Redis.RedisCacheHandle`1[TCacheValue].
info: CacheManager.Core.BaseCacheManager[0]
      Cache manager: adding cache handles...
info: CacheReflectionHelper[0]
      Creating handle redis-3 of type CacheManager.Redis.RedisCacheHandle`1[TCacheValue].
info: CacheManager.Core.BaseCacheManager[0]
      Cache manager: adding cache handles...
info: CacheReflectionHelper[0]
      Creating handle redis-4 of type CacheManager.Redis.RedisCacheHandle`1[TCacheValue].
The AttheTouchOfAButton.OptiOp.EventListener service is now running, press Control+C to exit.
info: CacheManager.Redis.RedisCacheHandle[0]
      Loading scripts.
info: CacheManager.Redis.RedisCacheHandle[0]
      DB 4 | Failed to add item 1d5a6466-cbe8-4732-b16b-da7ea156b158 because it exists.
```
This is how I'm calling the cache operations

 `_calibrationCache.AddOrUpdate(guid.ToString("D"),` calibration, x => calibration);

**Comment by dariogriffo-fourth** [comment] 2016-12-21 13:15
Just to clarify, my process was hanging bc I configured 1000 retries with 100 msecs timeout, the question would be why is trying to add if the entity is already on Redis

**Comment by MichaCo** [comment] 2016-12-21 13:21
@dariogriffo-fourth AddOrUpdate eventually tries to add the item and will update in case the item exists already. So, the log message `Failed to add item 1d5a6466-cbe8-4732-b16b-da7ea156b158 because it exists` is totally fine and works as expected.
The log should also eventually have a row for the update though.

I'm not really sure what the issue is your are facing. Little bit hard to tell from the code you showed ;) Looks all fine to me so far. Can you maybe show me more detail or eventually provide code to reproduce the behavior? Thanks, M

**Comment by dariogriffo-fourth** [comment] 2016-12-21 17:09
That's the problem it was hanging on the retry loop without updating it. I waited for more than 2 minutes and nothing. There was no other interaction with the cache. I'm testing locally under controlled environment. Will see if I can reproduce it. I can add the configuration/setup of the cache also.

**Comment by MichaCo** [comment] 2017-02-07 17:50
@dariogriffo-fourth well, I cannot reproduce this at all with correctly setup systems. Closing it for now.
If you have more information of how to reproduce it, let me know

**Closed by MichaCo** 2017-02-07 17:50 UTC
