### ISSUE TITLE
Redis + RuntimeCacheHandle / Fallback Issue

### ISSUE THREAD

**Issue by djsolid** [MichaCo/CacheManager#108] opened 2016-11-13 21:47 UTC
I'm using the following configuration:

`settings`
`                        .WithJsonSerializer()`
 `                       .WithLogging(typeof(CacheLoggerFactory))`
 `                       .WithSystemRuntimeCacheHandle("inprocess")`
 `                       .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))`
 `                    .And`
 `                       .WithRedisConfiguration("redis.azure", conStr)`
 `                       .WithRedisBackplane("redis.azure")`
 `                       .WithRedisCacheHandle("redis.azure", true);`

From logging I always read:

`item NOT found in handle inprocess`
`item found in handle redis.azure`

If I remove 
`.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))`
then objects are being stored in the Runtime Cache - besides Redis - however with no expiration.

What is it that I'm missing?

**Comment by MichaCo** [comment] 2016-11-13 23:15
Your configuration looks fine, and I'm 99% sure that the expiration stuff is working fine ;)

There might be different reasons for your case that the item is not available in the first cache handle. For example, if you update an item, the updated value gets stored only in redis and gets removed from the in memory cache in your case. 
The next `Get` would then store the cache item again in memory, too.

You might have other Trace log messages like "...Evict from handles above..." or similar.

Also, the item might have been removed due to expiration or memory pressure.

Otherwise, if you think this is a but, let me know. In that case it would be great if you could provide some code to reproduce it.

**Comment by djsolid** [comment] 2016-11-14 18:00
Thanks for your swift response. Investigating the issue a bit more the following works:

```settings
    .WithJsonSerializer()
    .WithLogging(typeof(CacheLoggerFactory))
    .WithSystemRuntimeCacheHandle("inprocess")
    .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
    .And
    .WithJsonSerializer()
    .WithLogging(typeof(CacheLoggerFactory))
    .WithRedisConfiguration("redis.azure", conStr)
    .WithRedisBackplane("redis.azure")
    .WithRedisCacheHandle("redis.azure", true);```

I think that's easy to check from your side. My understanding is that if I use a serializer this gets attached on one handle not all. So the inprocess was doing JSON and the Redis binary.

Could that be the case? Is there a test you can run to verify it?

**Comment by djsolid** [comment] 2016-11-14 19:01
Scratch the above. It's not working. My mistake. Here is the info from the log. I have a simple (ASP.NET) page that just Gets item 5157 from the cache. I also have a region named "MyRegion"

```
Trace:	=>Get: 5157 MyRegion.
Trace:	=>Get: 5157 MyRegion: item NOT found in handle inprocess.
Trace:	=>Get: 5157 MyRegion: item found in handle redis.azure.
Trace:	=>Add to handles: 5157 MyRegion: with update mode Up.
Trace:	=>Add to handles: 5157 MyRegion: adding to handle 0.
```

Every time I press the button "GET" this is being written on the log. 

Does that help to reproduce? I'll also delete my previous message as to not be confusing.

**Comment by MichaCo** [comment] 2016-11-14 19:05
@djsolid regarding the first message: No that's not the case,
Serializer gets set globally, it doesn't matter in which order you configure those things except the things which are per configured per handle (like serialization).
The `.And` just goes back one level.

In addition to that, serialization is used only by distributed caches. The inprocess handle simply stores the data in memory, there is no need for serialization ;)

the following two configurations would do exactly the same thing
````
var cfgA = new CacheManager.Core.ConfigurationBuilder()
    .WithJsonSerializer()
    .WithDictionaryHandle("inprocess")
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
    .And                
    .WithRedisConfiguration("redis.azure", "...")
    .WithRedisBackplane("redis.azure")
    .WithRedisCacheHandle("redis.azure", true)
    .Build();

var cfgB = new CacheManager.Core.ConfigurationBuilder()
    .WithDictionaryHandle("inprocess")
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
    .And
    .WithJsonSerializer()
    .WithRedisConfiguration("redis.azure", "...")
    .WithRedisBackplane("redis.azure")
    .WithRedisCacheHandle("redis.azure", true)
    .Build();
````

**Comment by MichaCo** [comment] 2016-11-14 19:08
Ok, I think I know what is going wrong ;)
You probably do not use a singleton instance of cachemanager. So everytime before you do a `Get`, you get a new instance of CacheManager. That doesn't affect the redis cache because the data is cached out of process, but a new in-process cache instance is created every time, which is empty.

In any application, not only web sites, you have to use the same instance of the cache to make use of in process caching.
In ASP.NET, you usually use DI frameworks to handle singletons, but there are many ways to achieve that...

**Comment by djsolid** [comment] 2016-11-14 19:12
Hm, makes sense however I do use Singleton. I only have one instance of CacheManager that instantiate on Global.asax.cs in Application_Start. Then I use that through the App lifecycle.

Is there any chance that the issue is because of the Region feauture I'm using?

Or maybe because I'm using Put instead of Add?

**Comment by TMiNus** [comment] 2016-11-14 19:21
I can confirm that this work as intended and the problem is not related with CacheManager. I have been using those handles (local, redis) for quite a while.

**Comment by MichaCo** [comment] 2016-11-14 19:21
Nope, that just works in all my tests. And just tested it for you ;)
```` CSharp
var cacheB = new BaseCacheManager<string>(cfgB);
cacheB.Put("key", "value", "region");

var v = cacheB.Get("key", "region");
```` 

logs:
```` 
Trace: Put: key region.
Trace: Put: key region to handle inprocess.
Trace: Put: key region to handle redis.azure.
Trace: Put: key region: notifies backplane [change].

Get: key region.
Trace: Get: key region: item found in handle inprocess.
````

**Comment by TMiNus** [comment] 2016-11-14 19:22
I am 90% sure is more related to the singleton issue that @MichaCo mention. Can you use any DI or implement a singleton around your CacheManager instance?

**Comment by djsolid** [comment] 2016-11-14 19:23
OK. Problem found. (I think). 

If JSON serialization is enabled primitive types (string,int etc) get stored on the 1st level Cache. Objects don't.

If I switch to binary then it works as expected. Can you verify that?

**Comment by TMiNus** [comment] 2016-11-14 19:24
I use Json serialization and it works so it isn't that

**Comment by MichaCo** [comment] 2016-11-14 19:33
No I also cannot confirm that. 
And as I already said, serialization really doesn't have any impact on your 1st level cache as that one just stores data in memory and doesn't serialize at all.

**Comment by TMiNus** [comment] 2016-11-14 19:37
Double checked the logs in the app that I am using almost with your same configuration and it works. The only thing I don't have like you is that I am using the default expiration and timeout and configuring those for each item

**Comment by djsolid** [comment] 2016-11-14 20:08
Thank you both for working on it. Still nothing.

If I remove the expiration from the configuration it works. It also works if I remove the JSON Serialization. Most likely I'll skip the JSON serialization for now and continue to investigating.

Thanks

**Comment by TMiNus** [comment] 2016-11-14 20:20
Can you put a full log output, in the log that you posted above the item was being added to localcache after being found on redis, so that log was not complete because we are not seeing the next call where it is supposed to find the item in localcache

**Comment by MichaCo** [comment] 2016-12-20 17:43
Closing this now as I cannot reproduce it. If you still have issues and can provide me with a code example to reproduce it, please let me know.

**Closed by MichaCo** 2016-12-20 17:43 UTC
Labels: question
