### ISSUE TITLE
Cache Synchronization is not sending data to Redis (it's just working as Memory Cache)

### ISSUE THREAD

**Issue by jieverson** [MichaCo/CacheManager#156] opened 2017-05-19 19:32 UTC
I have this setting:
```
var cacheManager = CacheFactory.Build<Object>("dietCache", settings =>
{
    settings
        .WithSystemRuntimeCacheHandle("inProcessCache")
        .And
        .WithRedisConfiguration("redis", "{MY_CONNECTION_STRING_TO_AZURE_REDIS}")
        .WithMaxRetries(1000)
        .WithRetryTimeout(100)
        .WithRedisBackplane("redis")
        .WithRedisCacheHandle("redis", true);
});
```
I can confirm cache is working if I do:
```
cacheManager.Put("mykey", "oi");
var result = cacheManager.Get<String>("mykey");
Assert.IsTrue(result == "oi");
```
It's was working, so I wrote a nodejs code to get the data directly from Redis, and it wasn't stored there.
I realized it was just making Memory Cache (when I stop the process and restart it, the cache was lost).

I have no idea, since my settings was supposed to use Cache Synchronization.

**Comment by MichaCo** [comment] 2017-05-19 22:44
do you have any code to reproduce the behavior? 
How did you retrieve the key from Redis via nodejs? 
Note that CacheManager stores any keys as hash, which means, a normal "get mykey" will not return any value..

**Comment by jieverson** [comment] 2017-05-19 23:00
You are right.... I was trying to just normally "get mykey"

```
const redis = require("redis")
let cache = redis.createClient({MY_CONFIG_TO_REDIS})
cache.get('test-cache-manager',  (err, reply) => {
    response.end(reply)
})
cache.set('test-cache-manager', 'nodejs rules!', (err, reply) => {
    response.end(reply)
})
```

So, how could I check for data on Redis using node/other app?

Anyway, if Redis cache was working, I wouldn't lost my cache after restarting IIS process.

**Comment by MichaCo** [comment] 2017-05-19 23:26
you also did a set on the key, which would render the key unusable for CacheManager because, again, its not a hash. Maby that's why the key "disappeared" ;)
You can use any client, doesn't matter, your node.js client should be fine, too. Just do a `hgetall` instead of `get`. You can use redis-cli, or [redis desktop manager](https://redisdesktop.com/) is also a handy tool.

**Comment by jieverson** [comment] 2017-05-20 16:14
Yes, you ware right.... the set on node was making key unusuble for CacheManager... I stoped using node and start using `redis desktop manager`, and it's helping a lot.

**Thanks a lot!**

My problem now is: I would like to make sure sync is working, and I can't just change the value on Redis, cause it's not going to notify CacheManager.... how could I make sure it's is working.... that when I set something on client, it will not just set on Redis, but also at all other clients?

**Comment by MichaCo** [comment] 2017-05-20 17:12
@jieverson regarding the sync:
First let me ask, why do you plan to do changes outside of your app/CacheManager? And what actions are you going to do, delete only?

CacheManager currently does not support syncing data which gets **modified** outside of CacheManager. If you want to modify a value of a key outside of CacheManager, the value will not be synced. That might not really be an issue if you have very short expiration on the in-memory cache though...

If you really have to modify a lot outside of CacheManager and expect a high consistency, just don't use an additional in-memory cache.

That being said, Redis also supports key-space notifications and CacheManager currently supports that for expiration (like Redis expires/evicts a key, notifies cachemanager and all instances get synced...)
In the next version of CacheManager, that will work for `del`, too. Any manual delete of a key will sync...
I will not add an event listener for plain modifications though (like `hset`) as that would add a lot of network traffic / cross talk..

Hope that makes sense ;)
closing this for now as there seem to be no issue or additional feature request.

**Closed** 2017-05-20 17:34 UTC
Labels: question

**Comment by jieverson** [comment] 2017-05-20 17:56
Sure.... Actually, I'm not planning to change Redis outside of app/CacheManager.
I'm hosting a webapp on Azure, and it is current running in 1 instance using memory cache.
My problem is that I was planning to upgrade to 2~3 instances, but I would need to move to some kind of server cache (that's why I started looking at Redis). My problem is that, when I tried this setup, I lost a lot of performance to move from memory cache to Redis, and that is why I started looking at Cache Manager. I expect CacheManager can sync my 3 instances (same app) memory cache with Redis server. But I'm not sure if this is how CacheManager Sync works.... 

I can't work with very short expiration, cause I'm planning to use cache mostly for my server Session Data, which has a lot more Gets than Sets... But with different instances, I need to make sure when I change/delete session data from on instance, it will change/delete from Redis, and replicate to other instances.

**Comment by MichaCo** [comment] 2017-05-20 17:59
Ah, sure, that is exactly why the Backplane thing exists in CacheManager. If all your instances of your app use the same configuration (Redis connection and backplane channel), CacheManager will sync your in-memory. 
Just try it out locally, run a few instances of you app, enable logging and see if you get backplane notifications send around

**Comment by jieverson** [comment] 2017-05-20 18:01
Thanks, will do that :)

**Comment by jieverson** [comment] 2017-05-23 20:59
Sorry to take your time again.
Things are working great! but some of my cache are made by OutputCache, and I'm having a hard time findind any example of how to use and configure CacheManagerOutputCacheProvider from CacheManager.Web
