### ISSUE TITLE
Notification Not working as expected with different configurations

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#133] opened 2017-03-07 11:47 UTC
I have created two caches with different configurations ,with each configuration points different database instance in redis. When i update/remove an key in one cache it's getting notified to both the caches. 
Expectation:
As cache are different and different configurations with different database instances. Notification should be made with in the same configuration.

    var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
            {
                settings
                .WithSystemRuntimeCacheHandle("inProcessCacheA").WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(15))
                .And
                .WithRedisConfiguration("redisCacheA", config =>
                {
                    config.WithAllowAdmin()
                        .WithDatabase(0)
                        .WithEndpoint("192.168.138.97", 6379);
                })
                .WithMaxRetries(1000)
                .WithRetryTimeout(100)
                .WithRedisBackplane("redisCacheA")
                .WithRedisCacheHandle("redisCacheA", true); //.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(40))//.
                ;
            });

            var cacheConfig1 = ConfigurationBuilder.BuildConfiguration(settings =>
            {
                settings
                .WithSystemRuntimeCacheHandle("inProcessCacheB").WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(15))
                .And
                .WithRedisConfiguration("redisCacheB", config =>
                {
                    config.WithAllowAdmin()
                        .WithDatabase(1)
                        .WithEndpoint("192.168.138.97", 6379);
                })
                .WithMaxRetries(1000)
                .WithRetryTimeout(100)
                .WithRedisBackplane("redisCacheB")
                .WithRedisCacheHandle("redisCacheB", true) //.WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(40))//.
                ;
            });
            var cacheA = new BaseCacheManager<string>(cacheConfig);
            var cacheB = new BaseCacheManager<string>(cacheConfig1);
            cacheA.GetOrAdd("CacheA", "KeyValue Vijay");
            cacheB.GetOrAdd("CacheB", "KeyValue Vijay");

           // cacheA.OnAdd += CacheA_OnAdd1;
         //   cacheB.OnAdd += CacheB_OnAdd1;
         
            cacheA.OnRemove += CacheA_OnRemove1;
            cacheB.OnRemove += CacheB_OnRemove1;
            cacheA.OnUpdate += CacheA_OnUpdate;
            cacheB.OnUpdate += CacheB_OnUpdate1;
            cacheA.Update("CacheA", s => "Updated Value fOR CACHE a Hello!");
          cacheA.Remove("CacheA");
            Console.ReadKey();

        }

        private static void CacheB_OnUpdate1(object sender, CacheManager.Core.Internal.CacheActionEventArgs e)
        {
            Console.WriteLine("Update CacheA " + e.Key + e.Origin);
        }

        private static void CacheA_OnUpdate(object sender, CacheManager.Core.Internal.CacheActionEventArgs e)
        {
            Console.WriteLine("Update CacheA " + e.Key + e.Origin);
        }

**Comment by MichaCo** [comment] 2017-03-07 12:33
@vijay8059 This is acutally by design right now. Although I might change the behavior slightly because of exactly that reason and because it can be confusing.
But, in general, the backplane can be configured with a channelName. 
Right now, if you do not pass any channelName, a [default name will be used](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.StackExchange.Redis/RedisCacheBackplane.cs#L50).
This is way you are receiving messages from both cache managers, both backplanes are connected to the same pub/sub channel...

You can change that behavior by passing in a custom channel name in `.WithRedisBackplane("redisCacheB", "<channelName>")`...

I thought about changing the default fallback using the configuration key instead. But I'm not really sure as that can be different by mistake, or could also be the same by mistake, so, it doesn't really solve the "issue". That's why it is like that today ;) 
hope that makes sense

**Comment by MichaCo** [comment] 2017-03-10 06:35
seems you're good /closing for now

**Closed by MichaCo** 2017-03-10 06:35 UTC

**Comment by vijay8059** [comment] 2017-03-10 06:57
Yes. Thanks for the reply. It worked for me.
