### ISSUE TITLE
Cache manager locking threads

### ISSUE THREAD

**Issue by educosta** [MichaCo/CacheManager#339] opened 2021-05-27 02:49 UTC
I'm using cachemanager in a large project and often the site goes down because of the cachemanager

![image](https://user-images.githubusercontent.com/3913187/119758388-db55fd80-be7c-11eb-9373-64261fc800cd.png)

Can someone help me?

**Comment by codeex** [comment] 2021-05-27 03:22
The author dont modify code?

**Comment by MichaCo** [comment] 2021-05-30 23:27
closing for /duplicate of #300 

There was a potential deadlock in the RetryHelper.

I'll push a release soon which should fix it, PR should come soon. All the potential deadlock code will be gone and there shouldn't be anything causing deadlocks in CacheManager anymore.
If you still get them, then it might be because of the StackExchange.Redis client.

But lets see how the change goes - let me know

**Closed by MichaCo** 2021-05-30 23:27 UTC
