### ISSUE TITLE
Possible threading deadlock CacheFactory.FromConfiguration on Startup.cs in MVC application

### ISSUE THREAD

**Issue by tatarincev** [MichaCo/CacheManager#30] opened 2015-12-15 09:56 UTC
CacheManager.Core 0.6.1
In ASP.NET MVC 5.2.3

Startup.cs
```C#
//Freeze here (possible reason threading deadlock)
   var cacheManager = CacheFactory.FromConfiguration<object>("storefrontCache");
   container.RegisterInstance<ICacheManager<object>>(cacheManager); 
```
web.config

```XML
<cacheManager xmlns="http://tempuri.org/CacheManagerCfg.xsd">
		<managers>
			<cache name="storefrontCache" updateMode="Up" enableStatistics="true" enablePerformanceCounters="true">
				<handle ref="runtimeMemory" name="inMemoryCacheHandle" expirationMode="Absolute" timeout="10m"/>
			</cache>
		</managers>
		<cacheHandles>
			<handleDef id="runtimeMemory" type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching" />
		</cacheHandles>
	</cacheManager>
```

**Comment by MichaCo** [comment] 2015-12-15 14:54
This most likely has something todo with the System.Runtime.Caching `MemoryCache` instance and nothing with CacheManager in the first place.

Can you provide a full stack trace? Any other tracing information you might have? Where exactly does it stop?

Do you have any system.runtime.caching configuration in your web.config?

Also, take a look at this https://github.com/maartenba/MvcSiteMapProvider/issues/379, they seem to have similar issues.

**Comment by tatarincev** [comment] 2015-12-15 15:02
I will try tomorrow use CacheManager with pdb and provide to you stack trace.
Its freeze not always, often when i do some changes in code and rebuild project or change web.config (when IIS restarted).

here is my caching section in web.config
```xml
 <system.web>
        <compilation debug="true" targetFramework="4.5.1" />
        <httpRuntime targetFramework="4.5.1" />
		<caching>
			<outputCache defaultProvider="CacheManagerOutputCacheProvider">
				<providers>
					<add name="CacheManagerOutputCacheProvider" type="CacheManager.Web.CacheManagerOutputCacheProvider, CacheManager.Web" cacheName="storefrontCache" />
				</providers>
			</outputCache>
			<outputCacheSettings>
				<outputCacheProfiles>
					<add name="AssetsCachingProfile" enabled="true" location="ServerAndClient" duration="216000" varyByParam="*" />
					<add name="ProductCachingProfile" enabled="true" location="ServerAndClient" duration="216000" varyByParam="*" varyByCustom="user" />
					<add name="CatalogSearchCachingProfile" enabled="true" location="ServerAndClient" duration="216000" varyByParam="*" varyByCustom="user" />
					<add name="HomeCachingProfile" enabled="true" location="ServerAndClient" duration="216000" varyByParam="*" varyByCustom="user" />
				</outputCacheProfiles>
			</outputCacheSettings>
		</caching>
    </system.web>
```

**Comment by tatarincev** [comment] 2015-12-23 17:43
Its continiue freezed for all our team members. Also its cause some strange errors on Azure AppService when deployment. Maybe you have another memory cache handle implementation (AspNetCacheProvider or something manual impl)?

**Comment by MichaCo** [comment] 2015-12-24 13:07
He @tatarincev 
Unfortunately I cannot reproduce that behavior at all. I create different MVC web sites using exactly your configuration; ran it in IISExpress and local IIS. 
Restarted the app pool several times, reset the app via web.config change several times... 
No thread lock nor any exception happend at all during my tests.

Could you try to disable performance counters and see if this fixes your issue?

Like this:

    <cache name="storefrontCache" 
      updateMode="Up" 
      enableStatistics="false" 
      enablePerformanceCounters="false">

**Comment by tatarincev** [comment] 2015-12-24 13:10
Ok I will try with disabled statistics. Thanks.

**Comment by MichaCo** [comment] 2015-12-26 01:28
I just released v0.7.0 which now comes with a System.Web.Caching based cache handle (included in the Web package).
Hope that helps!

**Comment by tatarincev** [comment] 2015-12-29 09:24
Thanks will try this.

**Comment by tatarincev** [comment] 2015-12-29 10:40
Should be aware to using WebCache handle  in native thread. Its not working. (I try to use it inside Hangfire job)

**Comment by MichaCo** [comment] 2015-12-29 10:52
It requires `HttpContext.Current` to be not null, that's how that cache works... 
You don't instantiate the System.Web.Caching.Cache yourself (not even possible), the HttpContext initializes all the internal stuff...

That being said, `HttpContext.Current` has a setter, you *can* create a new HttpContext, for testing for example.

**Comment by MichaCo** [comment] 2015-12-29 10:53
But, just don't use it in environments where System.Web is not used and you don't have a request context. The normal System.Runtime.Caching memory cache should work just fine...

**Comment by tatarincev** [comment] 2015-12-29 10:54
Yes I did just that.

**Comment by MichaCo** [comment] 2016-01-12 08:45
@tatarincev can we close this issue?

**Comment by tatarincev** [comment] 2016-01-12 08:49
Yes sure, but dead lock for RuntimeMemory handle remains :(

**Comment by MichaCo** [comment] 2016-01-12 09:16
I cannot reproduce it at all unfortunately. Will close it for now

**Closed by MichaCo** 2016-01-12 09:16 UTC

**Comment by Vitalii-Efremov** [comment] 2016-09-20 12:55
Hi Michael,
We've found the problem and a solution. This hangs are caused by a CultureInfo that leaked
from a different AppDomain. More info about it and the solution in this article -http://www.zpqrtbnk.net/posts/appdomains-threads-cultureinfos-and-paracetamol

**Comment by MichaCo** [comment] 2016-09-20 13:11
Oh wow that's pretty interesting indeed! Thanks for sharing ;)
