### ISSUE TITLE
Using MemoryCacheHandle with RedisCacheBackplane but without RedisCacheHandle

### ISSUE THREAD

**Issue by rebulanyum** [MichaCo/CacheManager#111] opened 2016-11-22 13:29 UTC
On the documentation it says

    /// The cache manager must have at least one cache handle configured with <see cref="CacheHandleConfiguration.IsBackplaneSource"/> set to <c>true</c>.
    /// Usually this is the redis cache handle, if configured. It should be the distributed and bottom most cache handle.

I know how to do it with RedisCacheHandle, since it's given as example on Cachemanager's website

    var cache = CacheFactory.Build<int>("myCache", settings =>
    {
        settings
        .WithSystemRuntimeCacheHandle("inProcessCache")
        .And
        .WithRedisConfiguration("redis", config =>
        {
            config.WithAllowAdmin()
                .WithDatabase(0)
                .WithEndpoint("localhost", 6379);
        })
        .WithMaxRetries(1000)
        .WithRetryTimeout(100)
        .WithRedisBackplane("redis")
        .WithRedisCacheHandle("redis", true);
    });

The problem is I don't want to use Redis as cache resource; I just want to make a distributed cache by the power of Redis Pub/Sub mechanism. According to my debugging through the code, by using Redis Backplane feature I'm able to send messages to and receive messages from Redis indeed. So why not use RedisCacheHandle and instead use SystemRuntimeCacheHandle?

So, my expectation was the successfull execution with the following cache configuration

    var cache = CacheFactory.Build<int>("myCache", settings =>
    {
        settings
        .WithSystemRuntimeCacheHandle("inProcessCache")
        .And
        .WithRedisConfiguration("redis", config =>
        {
            config.WithAllowAdmin()
                .WithDatabase(0)
                .WithEndpoint("localhost", 6379);
        })
        .WithMaxRetries(1000)
        .WithRetryTimeout(100)
        .WithRedisBackplane("redis")
        .WithSystemRuntimeCacheHandle("inProcessCache", true);
    });

But it's not working. Can you please show me a solution? What am I doing wrong? Or, eventhough it's written in the documentation as 

> ...Usually this is the redis cache handle...

are there any way to use the cache synchronization feature without RedisCacheHandle?

http://stackoverflow.com/questions/40741986/using-memorycachehandle-with-rediscachebackplane-but-without-rediscachehandle

**Comment by MichaCo** [comment] 2016-11-22 13:55
I guess you with "nor working" you mean that the other caches do not get synced, e.g. if I delete a key from cacheA, it doesn't get deleted from cacheB?
Yes this is currently an expected behavior.

The backplane is intended to work with out of process caches where you have only one state.
With 2 instances of the cache both using system runtime caching, you have two totally disconnected in proc caches.

Normally, if you have a Redis layer and you remove a key from cache instance A, the item would be removed from the Redis layer. The message gets send to other instances of the same cache and would remove the key from any other cache layer but redis (the one marked as backplane source).
This means, we expect that the backplane source is already in sync.

Now what if you have an in-process cache as backplane source. That doesn't work, because both instances will always be out of sync.

Lets look at this example:

```` csharp
    var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
    {
        settings
        .WithSystemRuntimeCacheHandle("inProcessCache")
        .And
        .WithRedisConfiguration("redis", config =>
        {
            config.WithAllowAdmin()
                .WithDatabase(0)
                .WithEndpoint("localhost", 6379);
        })
        .WithMaxRetries(1000)
        .WithRetryTimeout(100)
        .WithRedisBackplane("redis")
        .WithSystemRuntimeCacheHandle("inProcessCache", true);
    });

    var cacheA = new BaseCacheManager<string>(cacheConfig);
    var cacheB = new BaseCacheManager<string>(cacheConfig);
            
    cacheB.Backplane.Removed += (obj, args) =>
    {
        Console.WriteLine(args.Key + " removed from B.");
    };

    cacheA.Add("key", "value");
            
    var result = cacheB.Get("key");
    Console.WriteLine("Result should be null:" + result);

    cacheB.Add("key", "value");
    result = cacheB.Get("key");
    Console.WriteLine("Result should not be null:" + result);

    // triggers backplane remove event
    cacheA.Remove("key");

    // lets give redis some time send messages
    Thread.Sleep(100);
            
    result = cacheB.Get("key");
    Console.WriteLine("Result should be null again but isn't:" + result);

    Console.ReadKey();
```` 

If you run this, you can see that the backplane event actually fires but because the only in-proc cache is the backplane source, the key does not get deleted.
That's why at the end, you still get the key returned back to you.

As I said, that is currently the expected behavior.

You could implement custom logic with listening to those events though.
(the events will change slightly in the next version, currently there are a few bugs and inconsistencies).

Also, don't expect that the backplane would transfer cache values over to other instances. That's not going to happen ever. CacheManager only sends key events, not the data because the data is handled by the out of process cache usually.
Meaning, if you have in-proc cache only with backplane, adding an item in cacheA, will NOT copy the item to cacheB! You might get a `change` event for the key on cacheB though. 

I hope that makes sense ;)

**Comment by MichaCo** [comment] 2016-11-22 13:57
lets discuss that on SO as you created a question there, too, which is good /closing it here.

**Comment by MichaCo** [comment] 2016-11-23 08:29
After reading that again on SO I think this is more like a feature request.

But again, I will not implement distributed caching with in memory caches, that's not something which is desirable and is a pretty complex thing. That's what stuff like Redis is meant for and tbh.

The only thing I'd see viable is to remove items from other in memory caches if that's the only layer and the back plane source. That way I can at least invalidate other instances, which kinda makes sense. 
The next time you do a get on the other instance, you'd get null (not found) and have to create the data again.
You have to create the cache item again and eventually do expensive operations to do so, but that's the trade off vs using a distributed cache.

**Comment by rebulanyum** [comment] 2016-11-24 05:31
That was exactly what I was talking about :). Thank you again for great effort on the product.

**Comment by tatarincev** [comment] 2017-04-24 10:32
Hi, is there any estimate for this requirement implementation? We also want to use this kind of cache invalidation without using redistributed Redis cache, because have lot of data serialization issues.

**Comment by MichaCo** [comment] 2017-04-24 11:37
@tatarincev Hi, I have not worked on this yet. I will give it a try soon though, I guess.
What kind of serialization issues due you have?

**Comment by tatarincev** [comment] 2017-04-24 11:47
To use Redis cache, all objects should be serializable and this required revision of whole application athitecture. Solution is using redis for cache invalidation will  allow to don't touch already exist code and make scale out on azure.

**Comment by MichaCo** [comment] 2017-04-24 15:10
Ok I couldn't resist and gave it a try. Fun fact, transporting the Add or Remove events just work.

One problem though:
If I use Redis as backplane source and Add or Update or Remove a cache key, this usually triggeres a `Change`, or `Remove` event through the backplane and removes the key from any **other** handle (which is not backplane source). Because I expect that the backplane source (Redis) is already in sync.
This means, if I use in-memory handles as backplane source, the event will be triggered with orgin=remote, but the item may still exist in the local cache (no-sync)

I could change this by determining if the source handle is actually a distributed cache or not.
But if I would just apply the same logic, on Add or Update, this would remove the key from any other instance using the in-memory cache on the same backplane channel.
This is not really what we want. That would mean that the key would exist only in one instance ever...
Example, 
* I add keyA to cacheA => keyA gets removed from cacheB
* I add keyA back to cacheB => keyA gets removed form cacheA
...

So, I have to determine if the cache handle is distributed or not and on any `change` event, I will just trigger the event and not remove the item.

On `Remove` or cache clear events though, I would have to remove the item locally, too.

I hope this is somewhat logical and understandable? ^^

---

After implementing a few changes I did a quick test:

First with normal Redis + backplane + in-memory cache 
```
    var config = new ConfigurationBuilder("Redis with Redis Backplane")
        .WithDictionaryHandle(false)
            .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(1))
        .And
        .WithRedisCacheHandle("redisConfig")
            .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(2))
        .And
        .WithRedisBackplane("redisConfig")
        .WithRedisConfiguration("redisConfig", "localhost,allowadmin=true", enableKeyspaceNotifications: true)
        .Build();

    var cacheA = new BaseCacheManager<string>(config);
    var cacheB = new BaseCacheManager<string>(config);
```
Now I subscribe to some events and add a key to cacheA. This should trigger cacheB.OnAdd with orgin:remote.
After a few seconds, both `OnRemoveByHandle` should be triggered, as I enabled keyspace notifications

```
   var key = "someKey";
    cacheA.OnRemoveByHandle += (s, args) =>
    {
        Console.WriteLine("A triggered removeByHandle: " + args.ToString() + " - key still exists? " + cacheA.Exists(key));
    };

    cacheB.OnRemoveByHandle += (s, args) =>
    {
        Console.WriteLine("B triggered removeByHandle: " + args.ToString() + " - key still exists? " + cacheA.Exists(key));
    };

    cacheA.OnAdd += (s, args) =>
    {
        Console.WriteLine("A triggered add: " + args.ToString());
    };

    cacheB.OnAdd += (s, args) =>
    {
        Console.WriteLine("B triggered add: " + args.ToString());
    };

    cacheA.Add("someKey", "some value");

    cacheB.Add("someKey", "some other value");
```

the line `cacheB.Add(...` doesn't actually trigger anything because the key already exists.

output looks fine:

```
A triggered add: CacheActionEventArgs :someKey - Local
B triggered add: CacheActionEventArgs :someKey - Remote
A triggered removeByHandle: CacheItemRemovedEventArgs :someKey - Expired 2 - key still exists? False
B triggered removeByHandle: CacheItemRemovedEventArgs :someKey - Expired 2 - key still exists? False

```

Ok, now I change the configuration to use in-memory as backplane source and removing the redis cache handle

```
var config = new ConfigurationBuilder("Redis with Redis Backplane")
    .WithDictionaryHandle(true)
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
    .And
    .WithRedisBackplane("redisConfig")
    .WithRedisConfiguration("redisConfig", "localhost,allowadmin=true", enableKeyspaceNotifications: true)
    //.WithMicrosoftLogging(new LoggerFactory().AddConsole(LogLevel.Debug))
    .Build();

var cacheA = new BaseCacheManager<string>(config);
var cacheB = new BaseCacheManager<string>(config);
```

and subscript to `OnRemove` as `OnRemoveByHandle` doesn't trigger remotely...
and manually remove the item after a few seconds.
```
cacheA.OnRemove += (s, args) =>
{
    Console.WriteLine("A triggered remove: " + args.ToString() + " - key still exists? " + cacheA.Exists(key));
};
cacheB.OnRemove += (s, args) =>
{
    Console.WriteLine("B triggered remove: " + args.ToString() + " - key still exists? " + cacheB.Exists(key));
};

Thread.Sleep(2000);
cacheA.Remove(key);
```

Result:
```
A triggered add: CacheActionEventArgs :someKey - Local
B triggered add: CacheActionEventArgs :someKey - Local
A triggered add: CacheActionEventArgs :someKey - Remote
B triggered add: CacheActionEventArgs :someKey - Remote
A triggered remove: CacheActionEventArgs :someKey - Local - key still exists? False
B triggered remove: CacheActionEventArgs :someKey - Remote - key still exists? False
```

Seems to work ;)

The changes are in CacheManager.Core.1.0.2-beta-1508, I would really appreciate it if you could give it a try and test it with the beta. I'll have to do more testing before I release that.
Changes are in https://github.com/MichaCo/CacheManager/commit/9c25376ce2c6de1aa431ff826ff6e7ea7f784396

**Comment by tatarincev** [comment] 2017-04-25 09:51
Thanks for very quick response and solution!
But our solution use on 0.8.0 version and we cannot update to latest version quickly. 

I made temporary workaround which allow to achieve  required behavior for 0.8.0 version and would to hear you opinion about it.
I made derived RedisCacheHandler2 which override all PUT and ADD methods to pass empty values to Redis (for prevent serialization issues and avoid revision of whole solution code).

```
 public class RedisCacheHandle2<TCacheValue> : RedisCacheHandle<TCacheValue>
        {
            public RedisCacheHandle2(CacheManagerConfiguration managerConfiguration, CacheHandleConfiguration configuration, ILoggerFactory loggerFactory, ICacheSerializer serializer) : base(managerConfiguration, configuration, loggerFactory, serializer)
            {
            }

            public override UpdateItemResult<TCacheValue> Update(string key, string region, Func<TCacheValue, TCacheValue> updateValue, int maxRetries)
            {
                updateValue = (x) => (TCacheValue)(object)string.Empty;
                return base.Update(key, region, updateValue, maxRetries);
            }
            protected override void PutInternalPrepared(CacheItem<TCacheValue> item)
            {
                item = item.WithValue((TCacheValue)(object)string.Empty);
                base.PutInternalPrepared(item);
            }
            protected override bool AddInternalPrepared(CacheItem<TCacheValue> item)
            {
                item = item.WithValue((TCacheValue)(object)string.Empty);
                base.AddInternalPrepared(item);
                return true;
            }
        }
```

and configure CacheManager to work with Azure and RuntimeMemory cache handlers with enabled `backplate` as described in your documentation.

```
 var cacheConfig = ConfigurationBuilder.BuildConfiguration(settings =>
            {
                settings
                .WithSystemRuntimeCacheHandle("inProcessCache")
                .And
                .WithRedisConfiguration("redis", config =>
                {
                    config.WithAllowAdmin()
                        .WithDatabase(0)
                        .WithEndpoint("redis-url", 6380)
                        .WithSsl()
                        .WithPassword("secret key");                        
                })
                .WithMaxRetries(1000)
                .WithRetryTimeout(100)
                .WithRedisBackplane("redis")
                .WithHandle(typeof(RedisCacheHandle2<>), "redis", true);
            });
```
And seems it works fine as expected, we are using InMemory cache handle for all working instances and using Redis only for distributed cache  invalidation:)
How do you think we can use this solution or is there any hidden problem?

**Comment by MichaCo** [comment] 2017-04-25 10:07
@tatarincev I cannot recommend your solution and will not test or support it. But, sure, why not. You'd have to test how that behaves if you have at least 2 instances of your app running. 

Does it leave the in-memory layer untouched if another instance changes the key?

Not 100% sure how much that has been changed since 0.8, but CacheManager just removes any keys which have been changed in the backplane source (redis). This means you might run into exactly the issue I had to solved with some changes...

Again, just test your solution. I cannot really give you a clear answer if that will fly ;)

**Comment by tatarincev** [comment] 2017-04-25 12:22
Sure we'll test it. About changes of cached data we do not care about it, because we use [Cache-Aside pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside) everywhere and do not have the practice to change cached values.

**Comment by MichaCo** [comment] 2017-06-03 12:46
This is now implemented and mostly tested and will be in the next release.

**Closed by MichaCo** 2017-06-03 12:46 UTC
Labels: enhancement, needs design

**Comment by rebulanyum** [comment] 2017-08-18 14:03
Thank you @MichaCo  for the great effort. It works like a parrot ;) 

> A triggered add: CacheActionEventArgs :someKey - Local
B triggered add: CacheActionEventArgs :someKey - Local
A triggered add: CacheActionEventArgs :someKey - Remote
B triggered add: CacheActionEventArgs :someKey - Remote

**Comment by erizzo** [comment] 2020-04-06 20:52
I think I've found a defect, or at least a "gap" in the support configuration.

If I have 2 processes [configured as described by Micha](https://github.com/MichaCo/CacheManager/issues/111#issuecomment-296699499), it's possible that one of the process' (let's call it P1) in-memory cache handle will contain a particular value while the other (P2) does not. For example, a situation with 2 instances of an API, where one instance has served (and thus cached) the object, but the other instance has not (yet) served a request for that key.
Now if something happens in P2 that would invalidate the cache for that key, a call to `Remove()` will not send the notification over the backplane. That's because of some code in `BaseCacheManager.RemoveInteral()`, [here](https://github.com/MichaCo/CacheManager/blob/dev/src/CacheManager.Core/BaseCacheManager.cs#L485-L542). Note that on lines 501 or 505, the bool result of `handle.Remove()` is used to set a variable called `result`. _Only_ if `result is true (line 524), will the backplane get notified of the removal. Which means, if none of the handles (in this configuration, there is only the in-memory handle), currently contains the value, its `Remove()` will return false and thus no backplane message, thus the other process is never told that the key was removed.

We encountered this in a real situation, the simplest workaround we found was to first `Store()` a dummy value under the key right before calling `Remove()`, which ensured that `Remove()` returned true and the backplane message got sent.

I consider this a bug in this specific configuration (in-memory handle with a backplane for distributed in-memory-only-data caching). @MichaCo do you agree? Should this Issue be re-opened, or should we open a new bug?

**Comment by MichaCo** [comment] 2020-04-06 21:07
Yeah I kinda agree that this doesn't work well without a real distributed cache. It is working fine though with a distributed cache because in that case that layer only returns false on remove if the key doesn't exist anymore, was removed by someone else etc.

So, yeah go ahead an create a separate issue for this. Not sure yet how to solve it though. Just removing the check is not an option

**Comment by erizzo** [comment] 2020-04-06 22:17
I created #311 and mentioned there a (perhaps naive) suggestion for a potential solution.
